FROM centos:centos6

MAINTAINER Jennifer Li (jennifer.li@appdynamics.com)

# Install Node.js 4.2.1
RUN yum install -y wget
RUN wget --no-check-certificate https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-x64.tar.gz

# Install npm
RUN cd /usr/local
RUN tar --strip-components 1 -xzf node-v4.2.1-linux-x64.tar.gz
RUN yum install -y vim
RUN yum install -y git
RUN yum install -y unzip
RUN yum -y install java-1.7.0-openjdk-devel

RUN echo "Node.js version: " && node -v